# Ex 2.4: Part 2 (Outside Class)

In [2]:
import pandas as pd

### Read the datafile File into a *pandas* Dataframe

In [6]:
df = pd.read_excel("Data/Global Superstore 2016.xlsx", "Orders", skiprows=0)

print(df.shape)
df.head()

Ex 2.4 Part 2
(51290, 24)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [4]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code              float64
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

# Q2.1:  Show the rows in North Carolina, Georgia and Virginia with Sales greater than $3,000 

- Sort by Segment (alphabetically),Â  Customer Name (alphabetically), and Sales (Greatest to Least)

In [10]:
states = ['North Carolina', 'Georgia', 'Virginia']
df_Q1 = df.query("State in @states and Sales > 3000")
df_Q1.sort_values(by=['Segment', 'Customer Name', 'Sales'], ascending=[True, True, False], inplace=True)


print("Ex 2.4 Part 2: Show the rows in North Carolina, Georgia and Virginia with Sales greater than $3,000 ")
print(df_Q1.shape)
df_Q1

Ex 2.4 Part 2: Show the rows in North Carolina, Georgia and Virginia with Sales greater than $3,000
(6, 24)

C:\Users\W10\AppData\Local\Temp\ipykernel_14400\2625474130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Q1.sort_values(by=['Segment', 'Customer Name', 'Sales'], ascending=[True, True, False], inplace=True)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
11123,31806,CA-2013-CM12385140-41349,2013-03-16,2013-03-22,Standard Class,CM-123851408,Christopher Martinez,Consumer,30318.0,Atlanta,...,OFF-BI-4276,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750,581.12,Medium
30166,40936,CA-2013-JH15985140-41301,2013-01-27,2013-01-30,Second Class,JH-159851408,Joseph Holt,Consumer,28027.0,Concord,...,FUR-TA-3753,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical
46386,39785,CA-2014-SE20110140-41672,2014-02-02,2014-02-04,Second Class,SE-201101408,Sanjit Engle,Consumer,22204.0,Arlington,...,TEC-MA-4768,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840,17.83,Critical
23110,31980,US-2015-GT14635140-42313,2015-11-05,2015-11-05,Same Day,GT-146351408,Grant Thornton,Corporate,27217.0,Burlington,...,TEC-MA-3855,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904,674.82,High
23376,34577,CA-2012-GM14695140-41003,2012-04-04,2012-04-08,Second Class,GM-146951408,Greg Maxwell,Corporate,22304.0,Alexandria,...,OFF-SU-5168,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,4164.050,5,0.0,83.2810,846.54,High
33930,38880,CA-2012-KH16690140-40988,2012-03-20,2012-03-24,Standard Class,KH-166901408,Kristen Hastings,Corporate,22153.0,Springfield,...,TEC-PH-5822,Technology,Phones,Samsung Galaxy S4 Active,3499.930,7,0.0,909.9818,305.29,Medium